"""Derive database NOT NULL constraints from the profile.

A property the profile marks required, with no default, can only be satisfied if
its bound column always has a value. Making that column NOT NULL pushes the
requirement out to PostgREST, which reports it in its OpenAPI schema, which is
what the GUI builds its forms from. The constraint then surfaces in the wizard
rather than at template generation.

Generating rather than hand-writing the DDL keeps the two in step: re-run with
--check after a profile change to see what has drifted.

    python -m src.tools.db_constraints            # emit the DDL
    python -m src.tools.db_constraints --check    # compare against a live API
"""
import argparse
import json
import sys
import urllib.request
from typing import Dict, List, Set, Tuple

from src.models.settings import get_profile_settings
from src.models.tosca.profile import collect_bindings, document_bindings, get_profile
from src.models.tosca.profile.resolver import Profile


def required_columns(profile: Profile, type_names: List[str] | None = None) -> Dict[str, Set[str]]:
    """Columns that must always hold a value, keyed by table.

    A required property with a default is excluded: the profile supplies the
    value, so the column may be null.
    """
    if type_names is None:
        type_names = profile.type_names("node_types")

    required: Dict[str, Set[str]] = {}

    # Document-level bindings name the template and its node templates. Nothing
    # marks them required in the profile, but a document without them is not
    # usable, so the columns behind them must always hold a value.
    for table, column in document_bindings(profile).values():
        if column:
            required.setdefault(table, set()).add(column)

    # A row belongs to exactly one node type, but sibling types share a table.
    # A column may therefore only be NOT NULL if every type that could produce
    # the row requires it - a property of one subtype has to stay nullable, or
    # rows of its siblings could never be written.
    per_type: List[Dict[str, Set[str]]] = []
    for type_name in type_names:
        try:
            bindings = collect_bindings(profile.resolve(type_name), profile)
        except (KeyError, ValueError):
            continue
        this_type: Dict[str, Set[str]] = {}
        for binding in bindings:
            # A list property maps rows of a child table onto entries, so it is
            # the entry's own properties that decide what each row must hold.
            for entry in binding.entry_bindings:
                if _is_mandatory(entry.definition) and entry.column:
                    this_type.setdefault(binding.table, set()).add(entry.column)

            if binding.column and _is_mandatory(binding.definition):
                this_type.setdefault(binding.table, set()).add(binding.column)
        per_type.append(this_type)

    for table in {table for columns in per_type for table in columns}:
        # Only types that actually bind the table get a say in it; a totals type
        # says nothing about the columns of a table it never reads.
        opinions = [columns[table] for columns in per_type if table in columns]
        shared = set.intersection(*opinions) if opinions else set()
        if shared:
            required.setdefault(table, set()).update(shared)

    return required


def _is_mandatory(definition: dict) -> bool:
    """Required, and with no default to fall back on."""
    return bool(definition.get("required")) and "default" not in definition


def to_ddl(required: Dict[str, Set[str]]) -> str:
    """Render the constraints as a transactional migration."""
    lines = [
        "-- Generated by: python -m src.tools.db_constraints",
        "-- Derived from properties the TOSCA profile marks required without a default.",
        "-- Existing NULLs in these columns must be filled before this will apply.",
        "",
        "BEGIN;",
        "",
    ]
    for table in sorted(required):
        for column in sorted(required[table]):
            lines.append(f"ALTER TABLE {table} ALTER COLUMN {column} SET NOT NULL;")
        lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    lines.append("-- PostgREST caches the schema; tell it to re-read:")
    lines.append("--   NOTIFY pgrst, 'reload schema';")
    return "\n".join(lines)


def live_required(api_url: str) -> Dict[str, Set[str]]:
    """Columns PostgREST already reports as required."""
    with urllib.request.urlopen(api_url, timeout=30) as response:
        spec = json.load(response)
    return {
        table: set(definition.get("required") or [])
        for table, definition in (spec.get("definitions") or {}).items()
    }


def compare(profile_required: Dict[str, Set[str]], db_required: Dict[str, Set[str]]) -> Tuple[list, list]:
    """Report columns the profile requires but the database does not, and vice versa."""
    missing, extra = [], []
    for table, columns in sorted(profile_required.items()):
        in_db = db_required.get(table, set())
        for column in sorted(columns - in_db):
            missing.append(f"{table}.{column}")
    for table, columns in sorted(db_required.items()):
        from_profile = profile_required.get(table, set())
        for column in sorted(columns - from_profile):
            # Keys and generated columns are structural, not profile-driven.
            if column.endswith("_id") or column == "id":
                continue
            extra.append(f"{table}.{column}")
    return missing, extra


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="Compare against a live PostgREST instead of emitting DDL")
    parser.add_argument("--api-url", default=None,
                        help="PostgREST root URL, required with --check")
    args = parser.parse_args(argv)

    profile = get_profile()
    required = required_columns(profile)

    if not args.check:
        print(to_ddl(required))
        return 0

    if not args.api_url:
        parser.error("--check needs --api-url")

    missing, extra = compare(required, live_required(args.api_url))
    print(f"Profile: {get_profile_settings().source}")
    print(f"Database: {args.api_url}\n")
    if missing:
        print("Required by the profile but nullable in the database:")
        for item in missing:
            print(f"  {item}")
    if extra:
        print("\nNOT NULL in the database but not required by the profile:")
        for item in extra:
            print(f"  {item}")
    if not missing and not extra:
        print("In step: every profile-required column is NOT NULL.")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
